# Workshop # 2

In [4]:
#Import Python Libraries
import numpy as np
import scipy as sp
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [5]:

df = pd.read_csv("titanic-train.csv")

df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [6]:
df2 = df.loc[:,['Survived', 'Pclass', 'Sex', 'Age', 'SibSp', 'Parch']]
df2

Survived  Pclass     Sex   Age  SibSp  Parch
0           0       3    male  22.0      1      0
1           1       1  female  38.0      1      0
2           1       3  female  26.0      0      0
3           1       1  female  35.0      1      0
4           0       3    male  35.0      0      0
5           0       3    male   NaN      0      0
6           0       1    male  54.0      0      0
7           0       3    male   2.0      3      1
8           1       3  female  27.0      0      2
9           1       2  female  14.0      1      0
10          1       3  female   4.0      1      1
11          1       1  female  58.0      0      0
12          0       3    male  20.0      0      0
13          0       3    male  39.0      1      5
14          0       3  female  14.0      0      0
15          1       2  female  55.0      0      0
16          0       3    male   2.0      4      1
17          1       2    male   NaN      0      0
18          0       3  female  31.0      1      0
19          1       3  female   NaN      0      0
20          0       2    male  35.0      0      0
21          1       2    male  34.0      0      0
22          1       3  female  15.0      0      0
23          1       1    male  28.0      0      0
24          0       3  female   8.0      3      1
25          1       3  female  38.0      1      5
26          0       3    male   NaN      0      0
27          0       1    male  19.0      3      2
28          1       3  female   NaN      0      0
29          0       3    male   NaN      0      0
..        ...     ...     ...   ...    ...    ...
861         0       2    male  21.0      1      0
862         1       1  female  48.0      0      0
863         0       3  female   NaN      8      2
864         0       2    male  24.0      0      0
865         1       2  female  42.0      0      0
866         1       2  female  27.0      1      0
867         0       1    male  31.0      0      0
868         0       3    male   NaN      0      0
869         1       3    male   4.0      1      1
870         0       3    male  26.0      0      0
871         1       1  female  47.0      1      1
872         0       1    male  33.0      0      0
873         0       3    male  47.0      0      0
874         1       2  female  28.0      1      0
875         1       3  female  15.0      0      0
876         0       3    male  20.0      0      0
877         0       3    male  19.0      0      0
878         0       3    male   NaN      0      0
879         1       1  female  56.0      0      1
880         1       2  female  25.0      0      1
881         0       3    male  33.0      0      0
882         0       3  female  22.0      0      0
883         0       2    male  28.0      0      0
884         0       3    male  25.0      0      0
885         0       3  female  39.0      0      5
886         0       2    male  27.0      0      0
887         1       1  female  19.0      0      0
888         0       3  female   NaN      1      2
889         1       1    male  26.0      0      0
890         0       3    male  32.0      0      0

[891 rows x 6 columns]

In [7]:
print('Age missing ', df2['Age'].isnull().sum())
print('PClass missing ', df2['Pclass'].isnull().sum())
print('SibSp missing ', df2['SibSp'].isnull().sum())
print('Parch missing ', df2['Parch'].isnull().sum())
print('Survived missing ', df2['Survived'].isnull().sum())

Age missing  177
PClass missing  0
SibSp missing  0
Parch missing  0
Survived missing  0


In [8]:
df2['Age'] = df2['Age'].fillna(df2['Age'].mean())

print('Age missing ', df2['Age'].isnull().sum())

Age missing  0


In [9]:
df2['Survived'] = df2['Survived'].astype('category')

In [10]:
from sklearn.model_selection import train_test_split

train_X, test_X, train_y, test_y = train_test_split(df2[['Pclass','Sex','Age','SibSp','Parch']], 
                                                    df2['Survived'], 
                                                    train_size=0.7, 
                                                    random_state=123)
print("Labels for training and testing data")
print(train_X)

Labels for training and testing data
     Pclass     Sex        Age  SibSp  Parch
416       2  female  34.000000      1      1
801       2  female  31.000000      1      1
512       1    male  36.000000      0      0
455       3    male  29.000000      0      0
757       2    male  18.000000      0      0
275       1  female  63.000000      1      0
121       3    male  29.699118      0      0
443       2  female  28.000000      0      0
458       2  female  50.000000      0      0
653       3  female  29.699118      0      0
725       3    male  20.000000      0      0
395       3    male  22.000000      0      0
754       2  female  48.000000      1      2
40        3  female  40.000000      1      0
217       2    male  42.000000      1      0
457       1  female  29.699118      1      0
732       2    male  29.699118      0      0
469       3  female   0.750000      2      1
250       3    male  29.699118      0      0
124       1    male  54.000000      0      1
470       3    mal

/Users/kris/anaconda3/anaconda/lib/python3.6/site-packages/sklearn/model_selection/_split.py:2026: FutureWarning: From version 0.21, test_size will always complement train_size unless both are specified.
  FutureWarning)


In [22]:
from sklearn import preprocessing

le = preprocessing.LabelEncoder()
le.fit(["male", "female"])
list(le.classes_)
train_X['Sex'] = le.transform(train_X['Sex'])

In [23]:
from sklearn.decomposition import PCA

pca = PCA(n_components=3)
pca.fit_transform(train_X)
print(pca.explained_variance_ratio_)

[0.98361654 0.00868067 0.00381721]


In [25]:
x_new = pca.transform(train_X) 
print(x_new)

[[ 4.14214163  0.82936344  0.39795316]
 [ 1.14350405  0.77262179  0.46107859]
 [ 6.19427921 -0.49379444  1.06050476]
 ...
 [ 2.15071229 -0.62121473 -0.76194324]
 [ 0.15162058 -0.65904249 -0.71985962]
 [-0.84792528 -0.67795637 -0.69881781]]
